import Mathlib.MeasureTheory.Measure.Restrict
import Mathlib.Probability.Independence.Basic
import Mathlib.Probability.Kernel.Composition.MeasureCompProd
import Mathlib.Probability.Kernel.CondDistrib

/-!
# Conditioning kernel provider bridges

This module pushes the conditioning hardbone one honest step beyond
`indepFun_of_history_entry_measurable_of_indep`: if a history parameter `H` is
measurable and independent from a current step `Z`, then the conditional
distribution of `Z` given `H` is the constant kernel `law(Z)`, and conditional
expectations of scalar functions `F (H omega) (Z omega)` reduce to
frozen-parameter integrals against that law.

The conclusion is deliberately conditioned on `MeasurableSpace.comap H`. Lifting
this reduction from the sigma-algebra generated by `H` to a larger history
sigma-algebra remains an explicit separate task.
-/

namespace HighDimProb

open MeasureTheory
open scoped ProbabilityTheory

noncomputable section

/-- Convert independence from an explicit history sigma-algebra into function
independence for a generic history parameter and current step. -/
theorem indepFun_of_measurable_of_indep_comap
    {Omega Alpha Beta : Type*}
    [MeasurableSpace Omega] [MeasurableSpace Alpha] [MeasurableSpace Beta]
    {P : Measure Omega} (mHist : MeasurableSpace Omega)
    (H : Omega -> Alpha) (Z : Omega -> Beta)
    (hH : @Measurable Omega Alpha mHist inferInstance H)
    (hIndep :
      ProbabilityTheory.Indep mHist (MeasurableSpace.comap Z inferInstance) P) :
    ProbabilityTheory.IndepFun H Z P := by
  rw [ProbabilityTheory.IndepFun_iff_Indep H Z P]
  refine ProbabilityTheory.indep_of_indep_of_le_left hIndep ?_
  exact (measurable_iff_comap_le).mp hH

/-- Freeze the history parameter and integrate only over the law of the current
step. This is the right-hand side produced by the kernel reduction. -/
noncomputable def frozenParameterIntegral
    {Omega Alpha Beta : Type*}
    [MeasurableSpace Omega] [MeasurableSpace Alpha] [MeasurableSpace Beta]
    (P : Measure Omega) (H : Omega -> Alpha) (Z : Omega -> Beta)
    (F : Alpha -> Beta -> Real) : Omega -> Real :=
  fun omega => MeasureTheory.integral (P.map Z) (fun z => F (H omega) z)

/-- Conditional expectation of `omega ↦ F (H omega) (Z omega)` with respect to
the sigma-algebra generated by `H`. -/
noncomputable def historyCondExp
    {Omega Alpha Beta : Type*}
    [MeasurableSpace Omega] [MeasurableSpace Alpha] [MeasurableSpace Beta]
    (P : Measure Omega) (H : Omega -> Alpha) (Z : Omega -> Beta)
    (F : Alpha -> Beta -> Real) : Omega -> Real :=
  MeasureTheory.condExp (MeasurableSpace.comap H inferInstance) P
    (fun omega => F (H omega) (Z omega))

/-- Under function independence, the conditional distribution of `Z` given `H`
is almost everywhere the constant kernel `law(Z)`. -/
theorem condDistrib_ae_eq_const_of_indepFun
    {Omega Alpha Beta : Type*}
    [MeasurableSpace Omega] [MeasurableSpace Alpha] [MeasurableSpace Beta]
    [StandardBorelSpace Beta] [Nonempty Alpha] [Nonempty Beta]
    {P : Measure Omega} [IsFiniteMeasure P]
    {H : Omega -> Alpha} {Z : Omega -> Beta}
    (hH : AEMeasurable H P)
    (hZ : AEMeasurable Z P)
    (hIndep : ProbabilityTheory.IndepFun H Z P) :
    Filter.EventuallyEq (MeasureTheory.ae (P.map H))
      (fun a => (ProbabilityTheory.condDistrib Z H P) a)
      (fun a => (ProbabilityTheory.Kernel.const Alpha (P.map Z)) a) := by
  refine ProbabilityTheory.condDistrib_ae_eq_of_measure_eq_compProd (X := H) hZ ?_
  simpa [Measure.compProd_const] using
    (ProbabilityTheory.indepFun_iff_map_prod_eq_prod_map_map hH hZ).mp hIndep

/-- Kernel-form conditional expectation reduction for a measurable history
parameter and an independent current step.

This theorem conditions only on `MeasurableSpace.comap H`; it does not claim a
reduction for an arbitrary larger history sigma-algebra. -/
theorem historyCondExp_ae_eq_frozenParameterIntegral_of_indepFun
    {Omega Alpha Beta : Type*}
    [MeasurableSpace Omega] [MeasurableSpace Alpha] [MeasurableSpace Beta]
    [StandardBorelSpace Beta] [Nonempty Alpha] [Nonempty Beta]
    {P : Measure Omega} [IsFiniteMeasure P]
    {H : Omega -> Alpha} {Z : Omega -> Beta}
    {F : Alpha -> Beta -> Real}
    (hH : Measurable H)
    (hZ : AEMeasurable Z P)
    (hIndep : ProbabilityTheory.IndepFun H Z P)
    (hInt : Integrable (fun p : Prod Alpha Beta => F p.1 p.2)
      (P.map (fun omega => (H omega, Z omega)))) :
    Filter.EventuallyEq (MeasureTheory.ae P)
      (historyCondExp P H Z F)
      (frozenParameterIntegral P H Z F) := by
  have hBase := ProbabilityTheory.condExp_prod_ae_eq_integral_condDistrib'
    (X := H) (Y := Z) (f := fun p : Prod Alpha Beta => F p.1 p.2) hH hZ hInt
  have hKernel :
      Filter.EventuallyEq (MeasureTheory.ae P)
        (fun omega => (ProbabilityTheory.condDistrib Z H P) (H omega))
        (fun omega => (ProbabilityTheory.Kernel.const Alpha (P.map Z)) (H omega)) := by
    exact MeasureTheory.ae_eq_comp hH.aemeasurable
      (condDistrib_ae_eq_const_of_indepFun hH.aemeasurable hZ hIndep)
  filter_upwards [hBase, hKernel] with omega hEq hKernelEq
  rw [hKernelEq, ProbabilityTheory.Kernel.const_apply] at hEq
  simpa [historyCondExp, frozenParameterIntegral] using hEq

/-- If the frozen-parameter integrals have a deterministic bound `B`, then the
conditional expectation along `H` is almost surely bounded by `B (H omega)`. -/
theorem historyCondExp_le_of_indepFun_under_uniform_bound
    {Omega Alpha Beta : Type*}
    [MeasurableSpace Omega] [MeasurableSpace Alpha] [MeasurableSpace Beta]
    [StandardBorelSpace Beta] [Nonempty Alpha] [Nonempty Beta]
    {P : Measure Omega} [IsFiniteMeasure P]
    {H : Omega -> Alpha} {Z : Omega -> Beta}
    {F : Alpha -> Beta -> Real} {B : Alpha -> Real}
    (hH : Measurable H)
    (hZ : AEMeasurable Z P)
    (hIndep : ProbabilityTheory.IndepFun H Z P)
    (hInt : Integrable (fun p : Prod Alpha Beta => F p.1 p.2)
      (P.map (fun omega => (H omega, Z omega))))
    (hBound : forall a,
      MeasureTheory.integral (P.map Z) (fun z => F a z) <= B a) :
    Filter.EventuallyLE (MeasureTheory.ae P)
      (historyCondExp P H Z F)
      (fun omega => B (H omega)) := by
  have hEq := historyCondExp_ae_eq_frozenParameterIntegral_of_indepFun
    (P := P) (H := H) (Z := Z) (F := F) hH hZ hIndep hInt
  filter_upwards [hEq] with omega hEqOmega
  rw [hEqOmega]
  exact hBound (H omega)

end

end HighDimProb