import HighDimProb.RandomMatrix.Basic
import Mathlib.Probability.Independence.Basic

/-!
# Conditioning expectation provider bridges

This module records the smallest honest independence bridge needed by the
conditional-expectation Tropp step audit.

It does not prove the full conditional-expectation trace-exp reduction. It only
shows how an arbitrary history sigma-algebra assumption can be converted into
the `IndepFun` shape consumed by existing downstream statements when the history
matrix is measurable with respect to that sigma-algebra.
-/

namespace HighDimProb

open MeasureTheory

/-- Convert independence from an explicit history sigma-algebra into function
independence for a history random matrix and the current random step.

This is the honest bridge missing from the current hardbone conditioning story:
if the history matrix entries are measurable with respect to `mHist`, and
`mHist` is independent of the sigma-algebra generated by `Z`, then the matrix
valued functions `H` and `Z` are independent.

This theorem does not prove any conditional-expectation inequality by itself. -/
theorem indepFun_of_history_entry_measurable_of_indep
    {Omega : Type*} [mOmega : MeasurableSpace Omega]
    {P : Measure Omega} {n : Nat}
    (mHist : MeasurableSpace Omega)
    (H Z : @RandomMatrix Omega mOmega n n)
    (hHmeas :
      forall i j,
        @Measurable Omega Real mHist inferInstance
          (fun omega => H omega i j))
    (hIndepSigma :
      ProbabilityTheory.Indep mHist (MeasurableSpace.comap Z inferInstance) P) :
    @ProbabilityTheory.IndepFun Omega _ _ mOmega _ _ H Z P := by
  have hHmeasSub :
      @Measurable Omega (Matrix (Fin n) (Fin n) Real) mHist inferInstance H := by
    refine measurable_pi_lambda _ ?_
    intro r
    refine measurable_pi_lambda _ ?_
    intro c
    simpa using hHmeas r c
  rw [ProbabilityTheory.IndepFun_iff_Indep H Z P]
  refine ProbabilityTheory.indep_of_indep_of_le_left hIndepSigma ?_
  exact (measurable_iff_comap_le).mp hHmeasSub

end HighDimProb
