import HighDimProb.RandomMatrix.Provider.Concentration

#check HighDimProb.matrixExpScaledIntegrable_of_provider_statement_of_finiteMeasure
#check HighDimProb.matrixBernsteinQuadraticFormUpperTail_of_naturalStateProviderAssumptions_tailSubsetDischarged_of_randomSelfAdjoint
#check HighDimProb.troppMasterTraceMGFStep_of_leftRight
#check HighDimProb.troppMasterTraceMGFFiniteFamily_generatedHistory_of_bernsteinPrimitives
#check HighDimProb.MatrixBernstein.operatorNormTail_of_primitives
#check HighDimProb.MatrixBernstein.optimized_of_primitives
#check HighDimProb.MatrixBernstein.CenteredRankOneExactRowInputs
#check HighDimProb.MatrixBernstein.centeredRankOneExactRow
#check HighDimProb.MatrixBernstein.sampleCovarianceExactRow
#check HighDimProb.MatrixBernstein.highProbability_of_primitives
