import HighDimProb.Scalar
import HighDimProb.Concentration
import HighDimProb.Vector
import HighDimProb.Geometry
import HighDimProb.RandomMatrix
import HighDimProb.Process
import HighDimProb.Statements
import HighDimProb.Experimental

open HighDimProb

#check Event
#check ProbabilityMeasure
#check RealRandomVariable
#check expect
#check centered
#check variance
#check upperTailProb
#check SubGaussianTail
#check markov_inequality
#check RandomVector
#check covarianceMatrix
#check IsotropicSecondMoment
#check SubGaussianVectorOrlicz
#check IsEpsilonNet
#check coveringNumber
#check maximalSeparatedNetStatement
#check GaussianWidthFunctional
#check RandomProcess
#check RandomSample
#check tailEventMeasurabilityStatement
#check packingCoveringInequalityStatement
#check RandomMatrix
#check matrixEntry
#check MeasurementMap
