import HighDimProb.Scalar
import HighDimProb.Analysis
import HighDimProb.Concentration
import HighDimProb.Distributions
import HighDimProb.Vector
import HighDimProb.Geometry
import HighDimProb.RandomMatrix
import HighDimProb.LimitTheorems
import HighDimProb.Process
import HighDimProb.Statements
import HighDimProb.Experimental

open HighDimProb

#check Event
#check ProbabilityMeasure
#check RealRandomVariable
#check expect
#check centered
#check variance
#check pow_le_two_sqrt_mul_exp_sq
#check upperTailProb
#check SubGaussianTail
#check markov_inequality
#check lintegral_ofReal_eq_lintegral_tail
#check subGaussianTail_of_psi2Bound
#check psi2Bound_of_subGaussianTail
#check psi1Bound_of_subExponentialTail
#check psi2BoundOfSubGaussianTailStatement
#check absMomentNat
#check absMomentNat_two_le_of_subGaussianTail
#check absMomentNat_le_of_subGaussianTail
#check subGaussianMomentNatOfSubGaussianTailStatement
#check SubGaussianMomentNatSqrt
#check subGaussianMomentNatSqrt_of_psi2Bound
#check CenteredSubGaussianMGFLIntegral
#check subGaussianTail_of_centeredSubGaussianMGF
#check psi2Bound_of_centeredSubGaussianMGF
#check centeredSubGaussianMGF_rademacher
#check subGaussianTail_rademacher
#check RandomVector
#check covarianceMatrix
#check IsotropicSecondMoment
#check SubGaussianVectorOrlicz
#check IsEpsilonNet
#check coveringNumber
#check maximalSeparatedNetStatement
#check GaussianWidthFunctional
#check RandomProcess
#check RandomSample
#check tailEventMeasurabilityStatement
#check packingCoveringInequalityStatement
#check RandomMatrix
#check matrixEntry
#check rowDot
#check sampleMean
#check IndependentFinSample
#check weakLawChebyshevBoundStatement
#check MeasurementMap
