import HighDimProb.Examples

/-!
Compact aggregate checks for the public examples surface. Focused API coverage
belongs in the corresponding `HighDimProbTest` and `HighDimProbJudge` files;
this test only verifies that the reader-facing example routes remain imported
through `HighDimProb.Examples`.
-/

#check HighDimProb.Examples.RandomMatrix.SampleCovarianceUsage.sampleCovariance_psd_usage
#check HighDimProb.Examples.RandomMatrix.SampleCovarianceTailUsage.sampleCovariance_quadraticForm_tail_usage
#check HighDimProb.Examples.RandomMatrix.SampleCovarianceTailUsage.sampleCovariance_operatorNorm_tail_usage
#check HighDimProb.Examples.RandomMatrix.SampleCovarianceTailUsage.sampleCovariance_exactRow_centeredSquare_quadraticForm_tail_usage
#check HighDimProb.Examples.RandomMatrix.SampleCovarianceTailUsage.sampleCovariance_exactRow_centeredSquare_operatorNorm_tail_usage
#check HighDimProb.Examples.RandomMatrix.RankOneMatrixBernsteinPipelineUsage.rankOne_operatorNormTail
#check HighDimProb.Examples.RandomMatrix.RandomFeatureKernelUsage.randomFeatureKernel_quadTail_opt_of_tropp
#check HighDimProb.Examples.RandomMatrix.NTKGramUsage.ntkGram_operatorNormTail
#check HighDimProb.Examples.RandomMatrix.EmpiricalFisherOperatorNormUsage.empiricalFisher_operatorNorm_tail_usage
#check HighDimProb.Examples.RandomMatrix.AttentionFeatureGramOperatorNormUsage.attentionFeatureGram_operatorNorm_tail_usage
#check HighDimProb.Examples.RandomMatrix.AttentionFeatureGramOperatorNormUsage.attentionFeatureGram_empirical_sub_mean
#check HighDimProb.Examples.RandomMatrix.AttentionFeatureGramOperatorNormUsage.attentionFeatureGram_operatorNormTail
#check HighDimProb.Examples.RandomMatrix.AttentionFeatureGramOperatorNormUsage.attentionFeatureGram_normalizedTail
#check HighDimProb.Examples.RandomMatrix.AttentionFeatureGramOperatorNormUsage.attentionFeatureGram_highProbability
#check HighDimProb.Examples.RandomMatrix.AttentionFeatureGramOperatorNormUsage.attentionFeatureGram_matrixLESandwich
#check HighDimProb.Examples.RandomMatrix.LoRAAdapterSubspaceCovarianceUsage.loraCovariance_operatorNormTail
#check HighDimProb.Examples.RandomMatrix.LoRAAdapterSubspaceCovarianceUsage.loraCovariance_normalizedTail
#check HighDimProb.Examples.RandomMatrix.LoRAAdapterSubspaceCovarianceUsage.loraCovariance_highProbability
#check HighDimProb.Examples.RandomMatrix.LoRAAdapterSubspaceCovarianceUsage.loraCovariance_matrixLESandwich
#check HighDimProb.Examples.RandomMatrix.NaturalTroppPipelineUsage.naturalTropp_traceState_zero_usage
#check HighDimProb.Examples.PrecisionDA.CovarianceTraceExpansionUsage.shrinkage_covariance_trace_expansion_usage
