import HighDimProb.Experimental

open HighDimProb

#check RandomVector
#check IsRandomVector
#check coord
#check coordinate
#check linearForm
#check sqNorm
#check euclideanNorm
#check mean
#check centered
#check Centered
#check variance
#check covariance
#check secondMoment
#check meanVector
#check centeredVector
#check CenteredVector
#check secondMomentMatrix
#check covarianceMatrix
#check IsotropicSecondMoment
#check IsotropicSecondMomentMatrix
#check IsotropicCovariance
#check IsotropicMarginal
#check IsIsotropic
#check marginal
#check directionNorm
#check directionScale
#check SubGaussianVectorOrlicz
#check HasSubGaussianVectorOrlicz
#check SubGaussianVectorTail
#check SubGaussianVectorMoment
#check CenteredSubGaussianVectorMGF
#check epsilonRadius
#check epsilonERadius
#check IsEpsilonNet
#check IsInternalEpsilonNet
#check IsEpsilonSeparated
#check externalCoveringNumber
#check coveringNumber
#check packingNumber
#check RandomMatrix
#check matrixEntry
#check RandomProcess
#check processAt
#check GaussianWidthFunctional
#check RandomSample
#check sampleEvaluation
#check MeasurementMap
#check ReconstructionMap
