import HighDimProb.Experimental

open HighDimProb

#check RandomVector
#check IsRandomVector
#check coord
#check coordinate
#check linearForm
#check sqNorm
#check euclideanNorm
#check mean
#check centered
#check Centered
#check variance
#check covariance
#check secondMoment
#check meanVector
#check centeredVector
#check CenteredVector
#check centeredVector_iff_forall_centered_coord
#check centered_centered
#check secondMomentMatrix
#check covarianceMatrix
#check IsotropicSecondMoment
#check IsotropicSecondMomentMatrix
#check isotropicSecondMomentMatrix_iff_isotropicSecondMoment
#check IsotropicCovariance
#check IsotropicMarginal
#check IsIsotropic
#check marginal
#check directionNorm
#check directionScale
#check SubGaussianVectorOrlicz
#check HasSubGaussianVectorOrlicz
#check SubGaussianVectorTail
#check SubGaussianVectorMoment
#check CenteredSubGaussianVectorMGF
#check RandomMatrix
#check matrixEntry
#check IsRandomMatrix
#check rowVector
#check colVector
#check isRandomVector_rowVector
#check isRandomVector_colVector
#check matVec
#check vecMat
#check isRandomVector_matVec
#check isRandomVector_vecMat
#check frobeniusSq
#check frobeniusNorm
#check entrywiseMaxAbs
#check isRealRandomVariable_frobeniusSq
#check isRealRandomVariable_frobeniusNorm
#check SubGaussianEntriesOrlicz
#check SubGaussianEntriesTail
#check SubGaussianRowsOrlicz
#check IsotropicRowsSecondMoment
#check IsotropicRowsCovariance
#check CenteredEntries
#check gramMatrixEntry
#check gramMatrix
#check rowGramMatrixEntry
#check rowGramMatrix
#check sampleCovarianceEntry
#check sampleCovariance
#check isRealRandomVariable_gramMatrixEntry
#check isRealRandomVariable_rowGramMatrixEntry
#check isRealRandomVariable_sampleCovarianceEntry
#check quadraticForm
#check bilinearForm
#check isRealRandomVariable_quadraticForm
#check isRealRandomVariable_bilinearForm
#check operatorNorm
#check epsilonRadius
#check epsilonERadius
#check IsEpsilonNet
#check IsInternalEpsilonNet
#check IsEpsilonSeparated
#check MaximalEpsilonSeparatedIn
#check isInternalEpsilonNet_of_maximalEpsilonSeparatedIn
#check externalCoveringNumber
#check coveringNumber
#check packingNumber
#check maximalSeparatedNetStatement
#check epsilonNetCoveringNumberStatement
#check packingCoveringInequalityStatement
#check RandomProcess
#check processAt
#check GaussianWidthFunctional
#check RandomSample
#check sampleEvaluation
#check MeasurementMap
#check ReconstructionMap
