import HighDimProb.Concentration.Hoeffding

open HighDimProb

#check centeredSubGaussianMGF_of_ae_mem_Icc_of_centered
#check centeredSubGaussianMGF_of_forall_mem_Icc_of_centered
#check expect_finset_sum
#check iIndepFun_centered_of_iIndepFun
#check ae_mem_Icc_centered_of_ae_mem_Icc
#check sum_centered_eq_sum_sub_expect_sum
#check centeredSubGaussianMGF_sum_of_iIndepFun_bounded_centered
#check subGaussianTail_sum_of_iIndepFun_bounded_centered
#check upperTailProb_le_exp_neg_two_mul_sq_div_of_mgf_eighth
#check lowerTailProb_le_exp_neg_two_mul_sq_div_of_mgf_eighth
#check absTailProb_le_two_mul_exp_neg_two_mul_sq_div_of_mgf_eighth
#check hoeffding_sum_bounded_centered
#check hoeffding_sum_bounded_centered_sharp
#check hoeffding_sum_bounded
