import HighDimProb.Concentration.MGF

open HighDimProb

#check CenteredSubGaussianMGFLIntegral
#check centeredSubGaussianMGFLIntegral_of_centeredSubGaussianMGF
#check upperTailProb_le_exp_neg_sq_of_centeredSubGaussianMGFLIntegral
#check lowerTailProb_le_exp_neg_sq_of_centeredSubGaussianMGFLIntegral
#check upperTailProb_le_exp_neg_sq_of_centeredSubGaussianMGF
#check lowerTailProb_le_exp_neg_sq_of_centeredSubGaussianMGF
#check absTailEvent_subset_upperTailEvent_union_lowerTailEvent_neg
#check subGaussianTail_of_centeredSubGaussianMGFLIntegral
#check subGaussianTail_of_centeredSubGaussianMGF
#check psi2Bound_of_centeredSubGaussianMGF
#check subGaussianMomentNatSqrt_of_centeredSubGaussianMGF
