import HighDimProb
import HighDimProb.Basic
import HighDimProb.ProbabilitySpace
import HighDimProb.RandomVariable
import HighDimProb.Distribution
import HighDimProb.Expectation
import HighDimProb.Lp
import HighDimProb.Moment
import HighDimProb.Orlicz
import HighDimProb.SubGaussian
import HighDimProb.SubExponential
import HighDimProb.Tail
import HighDimProb.BookStatements

open HighDimProb

#check Event
#check ProbabilityMeasure
#check IsRealRandomVariable
#check law
#check expect
#check MemLpRealRandomVariable
#check realLpNorm
#check IntegrableRealRandomVariable
#check HasFiniteMoment
#check momentSeminorm
#check OrliczBound
#check Psi2Bound
#check Psi1Bound
#check HasFinitePsi2
#check HasFinitePsi1
#check SubGaussianTail
#check SubGaussianMoment
#check CenteredSubGaussianMGF
#check SubGaussianOrlicz
#check HasSubGaussianOrlicz
#check SubExponentialTail
#check SubExponentialMoment
#check CenteredSubExponentialMGF
#check SubExponentialOrlicz
#check HasSubExponentialOrlicz
#check absTailEvent
#check tailEventMeasurabilityStatement
