import HighDimProb
import HighDimProb.Init
import HighDimProb.Scalar
import HighDimProb.Statements

open HighDimProb

#check Event
#check ProbabilityMeasure
#check IsRealRandomVariable
#check law
#check expect
#check MemLpRealRandomVariable
#check realLpNorm
#check IntegrableRealRandomVariable
#check HasFiniteMoment
#check momentSeminorm
#check OrliczBound
#check Psi2Bound
#check Psi1Bound
#check HasFinitePsi2
#check HasFinitePsi1
#check SubGaussianTail
#check SubGaussianMoment
#check CenteredSubGaussianMGF
#check SubGaussianOrlicz
#check HasSubGaussianOrlicz
#check SubExponentialTail
#check SubExponentialMoment
#check CenteredSubExponentialMGF
#check SubExponentialOrlicz
#check HasSubExponentialOrlicz
#check absTailEvent
#check upperTailProb_antitone
#check lowerTailProb_monotone
#check absTailProb_antitone
#check tailEventMeasurabilityStatement
#check maximalSeparatedNetStatement
#check packingCoveringInequalityStatement
