import HighDimProb.RandomMatrix.LiebProvider
import HighDimProb.RandomMatrix.ConcentrationStatements

open MeasureTheory
open HighDimProb
open scoped MatrixOrder Matrix.Norms.Operator Matrix.Norms.L2Operator

#check operatorLogMonotoneOnPositiveMatrices
#check traceMatrixExp_mono_add_selfAdjoint
#check matrixExpFDeriv
#check hasFDerivAt_matrix_exp
#check hasStrictFDerivAt_matrix_exp
#check troppLogExpComparisonToK_of_providerLogOrder
#check EpsteinAffineLineConcavity
#check liebTraceExpConcavity_of_epsteinAffineLine
#check liebJensenTraceExp_statement_of_epsteinAffineLine
#check troppMasterTraceMGFStep_of_epsteinAffineLine
#check troppMasterTraceMGFStep_trace_bound_of_epsteinAffineLine_and_providerLogOrder
#check troppNaturalHistoryMeasurable_of_suffix_entry_measurable
#check matrixExpScaledIntegrable_of_provider_finiteMeasure
#check traceExpIntegrable_troppStateHistory_add_step_of_operatorNormBounds_finiteMeasure
#check traceExpIntegrable_troppStateHistory_add_K_of_operatorNormBounds_finiteMeasure
#check matrixExpSupportDomination_identity
#check lambdaMaxOrdered_le_of_matrixLE_selfAdjoint
#check lambdaMinOrdered_le_of_matrixLE_selfAdjoint
#check traceMGFBernsteinVarianceProxyBoundLIntegral_of_real
#check matrixBernsteinTraceMGFToLaplaceContract
#check matrixBernsteinTraceMGFToLaplaceContract_under_primitives
#check MatrixBernsteinConditioningTraceMGFProviderAssumptions
#check MatrixBernsteinConditioningTraceMGFProviderAssumptions.toTailAssumptions
#check matrixBernsteinQuadraticFormUpperTail_of_conditioningTraceMGFProviderAssumptions
#check matrixBernsteinQuadraticFormUpperTail_of_naturalStateProviderAssumptions
