import HighDimProb.RandomMatrix.RelativeEntropyProvider

open HighDimProb
open scoped MatrixOrder Matrix.Norms.L2Operator Matrix.Norms.Operator

#check RelativeEntropy.scalarTerm
#check RelativeEntropy.diagonalTerm
#check RelativeEntropy.diagonalMatrixTerm
#check RelativeEntropy.scalarTerm_nonneg
#check RelativeEntropy.diagonalTerm_nonneg
#check RelativeEntropy.diagonalMatrixTerm_eq_sum
#check RelativeEntropy.diagonalTerm_eq_diagonalMatrixTerm
#check RelativeEntropy.diagonalMatrixTerm_nonneg
#check kleinInequality_scalar_relativeEntropy_nonneg
#check kleinInequality_relativeEntropy_nonneg_diagonal
#check kleinInequality_relativeEntropy_nonneg_diagonal_matrix
#check RelativeEntropy.cfcLog_diagonal_eq_diagonal_log_of_pos
#check RelativeEntropy.trace_diagonal_mul_cfcLog_diagonal_eq_sum
#check RelativeEntropy.diagonalMatrixTerm_cfcLog_eq
#check RelativeEntropy.diagonalMatrixTerm_cfcLog_nonneg
#check kleinInequality_relativeEntropy_nonneg_diagonal_matrix_cfcLog
#check RelativeEntropy.commonEigenbasisWeight
#check RelativeEntropy.trace_mul_cfcLog_eq_sum_conj_diag_of_isHermitian
#check RelativeEntropy.trace_mul_cfcLog_eq_sum_commonEigenbasisWeight_of_isHermitian
#check RelativeEntropy.overlapWeight
#check RelativeEntropy.overlapWeight_nonneg
#check RelativeEntropy.commonEigenbasisWeight_self_eq_eigenvalue
#check RelativeEntropy.commonEigenbasisWeight_pos_of_isHermitian_of_isStrictlyPositive
#check RelativeEntropy.weightedSpectralKlein_nonneg
#check RelativeEntropy.overlapWeight_sum_right
#check RelativeEntropy.overlapWeight_sum_left
#check RelativeEntropy.commonEigenbasisWeight_eq_sum_overlapWeight_mul_eigenvalues
#check RelativeEntropy.trace_eq_sum_eigenvalues_of_isHermitian
#check RelativeEntropy.fullMatrixKlein_eq_weightedSpectralSum_of_isHermitian_of_strictlyPositive
#check RelativeEntropy.fullMatrixKlein_nonneg_of_isHermitian_of_strictlyPositive
#check RelativeEntropy.kleinInequality_relativeEntropy_nonneg
#check kleinInequality_relativeEntropy_nonneg
