import HighDimProb.RandomMatrix.ConditioningKernelProvider

namespace HighDimProbTest

#check HighDimProb.indepFun_of_measurable_of_indep_comap
#check HighDimProb.frozenParameterIntegral
#check HighDimProb.historyCondExp
#check HighDimProb.condDistrib_ae_eq_const_of_indepFun
#check HighDimProb.historyCondExp_ae_eq_frozenParameterIntegral_of_indepFun
#check HighDimProb.historyCondExp_le_of_indepFun_under_uniform_bound

end HighDimProbTest