import HighDimProb.Concentration.SubGaussianSums

open HighDimProb

#check isRealRandomVariable_finset_sum
#check isRealRandomVariable_finset_weighted_sum
#check hasSubgaussianMGF_finset_sum_of_iIndepFun
#check centeredSubGaussianMGF_finset_sum_of_iIndepFun_of_pos
#check centeredSubGaussianMGF_sum_of_iIndepFun_of_pos
#check subGaussianTail_finset_sum_of_iIndepFun_of_pos
#check subGaussianTail_sum_of_iIndepFun_of_pos
#check iIndepFun_weighted_of_iIndepFun
#check hasSubgaussianMGF_weighted_of_centeredSubGaussianMGF
#check hasSubgaussianMGF_finset_weighted_sum_of_iIndepFun
#check centeredSubGaussianMGF_finset_weighted_sum_of_iIndepFun_of_pos
#check centeredSubGaussianMGF_weighted_sum_of_iIndepFun_of_pos
#check subGaussianTail_finset_weighted_sum_of_iIndepFun_of_pos
#check subGaussianTail_weighted_sum_of_iIndepFun_of_pos
