#!/usr/bin/env python3
"""Generate a DOT graph of HighDimProb Lean imports.

This intentionally uses a line-based parser. It is meant for documentation and
drift checks, not for full Lean syntax analysis.
"""

from __future__ import annotations

from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = REPO_ROOT / "HighDimProb"
ROOT_FILE = REPO_ROOT / "HighDimProb.lean"
OUTPUT = REPO_ROOT / "docs" / "visualizations" / "import_graph.dot"


def module_name(path: Path) -> str:
    if path == ROOT_FILE:
        return "HighDimProb"
    rel = path.relative_to(REPO_ROOT).with_suffix("")
    return ".".join(rel.parts)


def lean_files() -> list[Path]:
    files = sorted(SOURCE_ROOT.rglob("*.lean"))
    if ROOT_FILE.exists():
        files.insert(0, ROOT_FILE)
    return files


def extract_imports(path: Path) -> list[str]:
    imports: list[str] = []
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line.startswith("import HighDimProb"):
            continue
        for token in line.split()[1:]:
            if token.startswith("HighDimProb"):
                imports.append(token)
    return imports


def dot_quote(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def write_dot(modules: set[str], edges: set[tuple[str, str]]) -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "// Generated by scripts/visualize_imports.py.",
        "// Direction: importer -> imported module.",
        "digraph HighDimProbImports {",
        "  rankdir=LR;",
        "  graph [fontname=\"Arial\", fontsize=10];",
        "  node [shape=box, style=\"rounded\", fontname=\"Arial\", fontsize=10];",
        "  edge [fontname=\"Arial\", fontsize=9];",
        "",
    ]
    for module in sorted(modules):
        lines.append(f"  {dot_quote(module)};")
    if edges:
        lines.append("")
    for src, dst in sorted(edges):
        lines.append(f"  {dot_quote(src)} -> {dot_quote(dst)};")
    lines.append("}")
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def root_modules(modules: set[str]) -> list[str]:
    roots: set[str] = set()
    for module in modules:
        parts = module.split(".")
        if module == "HighDimProb":
            roots.add(module)
        elif len(parts) >= 2 and parts[0] == "HighDimProb":
            roots.add(".".join(parts[:2]))
    return sorted(roots)


def main() -> int:
    modules: set[str] = set()
    edges: set[tuple[str, str]] = set()

    for path in lean_files():
        src = module_name(path)
        modules.add(src)
        for imported in extract_imports(path):
            modules.add(imported)
            edges.add((src, imported))

    write_dot(modules, edges)

    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)}")
    print(f"modules: {len(modules)}")
    print(f"import edges: {len(edges)}")
    print("root modules discovered:")
    for module in root_modules(modules):
        print(f"- {module}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
