import HighDimProb.RandomMatrix.LiebProvider
import HighDimProb.RandomMatrix.ConcentrationStatements

#check HighDimProb.operatorLogMonotoneOnPositiveMatrices
#check HighDimProb.traceMatrixExp_mono_add_selfAdjoint
#check HighDimProb.troppLogExpComparisonToK_of_providerLogOrder
#check HighDimProb.EpsteinAffineLineConcavity
#check HighDimProb.troppMasterTraceMGFStep_of_epsteinAffineLine
#check HighDimProb.troppMasterTraceMGFStep_trace_bound_of_epsteinAffineLine_and_providerLogOrder
#check HighDimProb.troppNaturalHistoryMeasurable_of_suffix_entry_measurable
#check HighDimProb.matrixExpScaledIntegrable_of_provider_finiteMeasure
#check HighDimProb.traceExpIntegrable_troppStateHistory_add_step_of_operatorNormBounds_finiteMeasure
#check HighDimProb.traceExpIntegrable_troppStateHistory_add_K_of_operatorNormBounds_finiteMeasure
#check HighDimProb.matrixExpSupportDomination_identity
#check HighDimProb.MatrixBernsteinConditioningTraceMGFProviderAssumptions
#check HighDimProb.matrixBernsteinQuadraticFormUpperTail_of_conditioningTraceMGFProviderAssumptions
