import HighDimProb.RandomMatrix.TraceExpIntegrabilityCompressionProvider

#check HighDimProb.matrixExpScaledIntegrable_of_provider_statement_of_finiteMeasure
#check HighDimProb.traceExpIntegrable_troppStateHistory_add_step_statement_of_summand_and_comparison_bounds_finiteMeasure
#check HighDimProb.traceExpIntegrable_troppStateHistory_add_K_statement_of_summand_and_comparison_bounds_finiteMeasure

